name: Webhost deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Installing node dependencies
        run: npm ci
      - name: Building for production
        run: npm run generate
      - name: Uploading to server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ${{ SSH_DESTINATION }}
          remote_host: ${{ SSH_HOST }}
          remote_user: ${{ SSH_USERNAME }}
          remote_key: ${{ SSH_KEY }}
          remote_port: ${{ SSH_PORT }}
